### ISSUE TITLE
start organizing benchmarks

### ISSUE THREAD

**Issue by scungao** [dreal/benchmarks#1]
@rachelwang @soonhokong Let's start working on this. 

I think we wanna break open the hybrid system folder, and just have a flat directory structure for different applications. In each folder it'll be about a particular problem, and can allow a bunch of different formats. So let's have:

benchmark/kepler
benchmark/quadcopter
benchmark/bouncingball
etc. 

For each folder we'll put a make file, a readme explaining the model, a page/file for results, etc.

**Comment by soonhokong** [comment]
@rachelwang, please add what you made for the recent submission. I'll migrate existing benchmarks from the dreal/dreal repo.

**Comment by rachelwang** [comment]
Models in my submission are hybrid model with random variables. I still
need to tune them to get the drh versions done.
I am busy with TA work today and even tomorrow. I will work on this over
the weekend. You can go ahead put your benchmarks first, and I will let you
know once I finishing preparing them.

Best,
Qinsi

**Comment by soonhokong** [comment]
@qinsi, I started adding `.drh` benchmarks to the repository. I think it's better to have `.pdrh` as it is. Please take a look at [nra_ode.mk](https://github.com/dreal/benchmark/blob/master/nra_ode.mk) and its usage in [prostate/Makefile](https://github.com/dreal/benchmark/blob/master/prostate_cancer/Makefile). I'm sure that you can come up with something like `nra_pdrh.mk` and `Makefile` for your benchmakrs. Let me know when you need a help.

**Comment by scungao** [comment]
sorta done, after 2+ years.

**Comment by soonho-tri** [comment]
Great!!!
